### ISSUE TITLE
CombineChargingSessions does not always combine

### ISSUE THREAD

**Issue by superfloh247** [bassmaster187/TeslaLogger#377]
example in my DB chargingstate id 996 997

charging at Lidl, Lidl disconnected after 60 minutes, restarted after 10 minutes (to walk over to the car). cable was never unplugged.

charging.pos differs, but pos.odometer is the same for both chargingstate.pos

find this pos.odometer with two charging sessions w/o moving the car:
select count(chargingstate.id), pos.odometer from chargingstate, pos where chargingstate.Pos = pos.id group by pos.odometer having count(chargingstate.id)>1 order by pos.odometer desc

result:
2 | 65917.4091523569
(and others)

next: find charging state IDs
select chargingstate.id, chargingstate.startdate, pos.odometer, pos.address, charging state.conn_charge_cable from chargingstate, pos where chargingstate.Pos = pos.id  and pos.odometer = 65917.4091523569

result:
996 | 2020-01-22 08:15:32 | 65917.4091523569 | 🔌 Lidl DE-Berlin Steglitzer Damm | IEC
997 | 2020-01-22 09:25:03 | 65917.4091523569 | 🔌 Lidl DE-Berlin Steglitzer Damm | IEC

cable did not change

next: combine into one charging session

todo: more plausibility checks, eg charging.charge_energy_added rises with each chargingstate.id

copy start date, pos, startchargingid from 996 to 997

todo: recalculate charging costs

delete 996

example that should not be combined: 1156 1157
cable changed!

another example that should be combined: 1005 1006 and 1042 1043

**Comment by Adminius** [comment]
I've also mailed my DB to @bassmaster187

**Comment by pbertra** [comment]
I also have the issue where : 
- I charge up to a given percentage
- Keep the car plugged in after charge (in my garage)
- The next day I decide to charge more before leaving (or preheat the car)
I this case, I get 2 charge sessions. The first one is the first part of the charge. The second one is the sum of both for the kWh...

Charging history ans stats are now a mess since it occurs quite frequently now.

**Comment by superfloh247** [comment]
This is work in progress https://github.com/superfloh247/TeslaLogger/tree/feature-closechargingstate-nextgen

**Comment by mss1010** [comment]
Hello, I have a similar issue, so I post my feeback here.
In the first charging sessions I recorded are looking wrong. The first one here from SOC 49 to 85 is correct. It shows 26,72 kWh charged. This was a planned charging session.

Then in the morning I manually started charging again just for 34 minutes. For this one it shows 27,03 kWh charged, which is impossible with a 4KW charger ;-) It seems that it added up the last session and shows the total of two session within the shorter one. The car was not moved between that. Also, the charging cable was not unplugged.

I am using Docker to run the logger.

![Unbenannt](https://user-images.githubusercontent.com/36116339/107410347-795fcb00-6b0d-11eb-8efa-1c9bf098d531.PNG)


[logfile.txt](https://github.com/bassmaster187/TeslaLogger/files/5953472/logfile.txt)

FYI: In the attached logfile I removed personal information like the GPS position.

@bassmaster187 @superfloh247 As you are working on the branch related to this, can you explain, if the charging history can be fixed afterwards, if the fix is available? Could users also fix it manually by editing DB entries?

**Comment by mss1010** [comment]
This issue seems to be solved with the current version. For me the wrong sessions were automatically corrected / combined. Perfect!

**Comment by superfloh247** [comment]
I think it's fixed
