### ISSUE TITLE
Calling Home feature towards teslalogger.de should be configurable 

### ISSUE THREAD

**Issue by Jagganaut** [bassmaster187/TeslaLogger#39]
for users without tasker it should be possible to terminate the initial callback to teslalogger.de

**Comment by bassmaster187** [comment]
This feature also send me your current teslalogger and car version, so I can consider this informations in new updates. In other words: if there is a known problem to update from version 3 to 10, but there is nobody using version 3, I can rule out anybody will have any problems. So I can save some extra time for a workaround. 

Plus it's nice for me to see there are a lot of teslaloggers still in use and my work is not just wasting my time.

I you really don't want to share this informations with me, just put teslalogger.de in your hostfile. Basically everything should work fine, because the update process depends on github.
