### ISSUE TITLE
TM3 2021 LR not detected correctly

### ISSUE THREAD

**Issue by filipkroca** [bassmaster187/TeslaLogger#443]
** Append Logfile **

#1: Car: M3 SR+ - 0.137 Wh/km

Related to #445 

**Describe the bug**

M3 2021 LR AWD EU 77 kWh is detected as M3 SR+

**Comment by thboegel** [comment]
Seems to be fixed for me since commit [https://github.com/bassmaster187/TeslaLogger/commit/14d831006784e97576dc6a47ba2f61057e962079](url)

`
14.03.2021 17:28:53 : #1: Economy from DB: 0.137 Wh/km - count: 3
14.03.2021 17:28:54 : #1: Streamingtoken: XXXXXXXXXX
14.03.2021 17:28:59 : Reverse geocoding by Nominatim1
14.03.2021 17:28:59 : #1: Country Code: de
14.03.2021 17:29:00 : #1: Car: M3 LR FL - 0.139 Wh/km
14.03.2021 17:29:00 : #1: VIN decoder: Model 3 2021 AWD:True MIC:False battery:NMC motor:3 dual
`
