### ISSUE TITLE
[FR] Support import of existing logs from TeslaFi

### ISSUE THREAD

**Issue by fiveangle** [bassmaster187/TeslaLogger#63]
For those of us who are current TeslaFi subscribers, it would be so incredibly useful to allow populating TeslaLogger with the historical logs from TeslaFi, even if only supported as a one-time import at start. 

Thanks for the interesting project !

**Comment by bassmaster187** [comment]
Hi Dave,

 

I don’t have a TeslaFi account as I would never give my Tesla credentials nor token to a third party. 

I can’t promise anything, because I don’t know if there are official TeslaFi API to pull ol the distorical logs.

I could make a Web Spider to grab all the Data from TeslaFi, but it would get obsolete after each change of their Webpage.

Would you share your TeslaFi credentials with me to be able to check what is possible and what not?

 

Thanks, 

Chris

 

Von: Dave Johnson [mailto:notifications@github.com] 
Gesendet: Dienstag, 13. August 2019 17:21
An: bassmaster187/TeslaLogger <TeslaLogger@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [bassmaster187/TeslaLogger] [FR] Support import of existing logs from TeslaFi (#63)

 

For those of us who are current TeslaFi subscribers, it would be so incredibly useful to allow populating TeslaLogger with the historical logs from TeslaFi, even if only supported as a one-time import at start.

Thanks for the interesting project !

**Comment by fiveangle** [comment]
Are you not familiar with the token mechanism for vehicle API access ?  All that is required to access the Tesla API stream is a valid token.  TeslaFi requires the same so you can either supply the credentials and have it auto-renew the token every 21 days (as you fear, giving the credentials for your account), or you can supply your own generated token to TeslaFi and revoke it immediatley afterwards (or at your leisure).

You can create an evaluation account on TeslaFI if you want to review directly, but they provide a very simple RAW data interface that provides all info in the form as attached when their php form is supplied with the date in "2019-08-13" format.  I'd imagine the fields would change any time the Tesla API changed but otherwise would remain fixed.  For import, TeslaLogger would need to repeatedly query https://teslafi.com/data.php, iterating through each day until the dataset because empty (or whatever happens when the feed hits the first instance... would need to experiment to determine.

I've removed potentially identifiable info or hashes from the compressed html scrape of the https://teslafi.com/data.php form:

[Tesla API Raw Data.zip](https://github.com/bassmaster187/TeslaLogger/files/3498836/Tesla.API.Raw.Data.zip)

**Comment by fiveangle** [comment]
You may also want to review the limitations of TeslaFi due to the non-storage of the user credentials:

https://about.teslafi.com/security/

I'm not stating they should be trusted, just that it does appear they are trying their best to do the right thing (for now).  That said, like you, I much prefer to be the master of my own destiny because no entity is in control of their unknown data breaches nor can they monitor the activity of every account as if it were their own.

-=dave

**Comment by fiveangle** [comment]
Looks like default RAW feed headers doesn't include all necessary fields such as GPS coordinates, so would need to probably iterate through header form data then enable relevant ones in the header form, then begin scraping.  Once designed, you could probably rely on your program to perform the scrapping on other users TeslaFI accounts, and when a change was found, build in a notification of the change and suggest user to review the github 🤷‍♂ 

![teslafi_raw_data_headers-2019-08-13_1415](https://user-images.githubusercontent.com/2219447/62977912-dec9e300-bdd4-11e9-8bf7-6d0e78c71820.png)

**Comment by bassmaster187** [comment]
https://github.com/bassmaster187/TeslaLogger/blob/master/TeslaFi-Import/README.md
