### ISSUE TITLE
Supercharger Hasselt / Belgium

### ISSUE THREAD

**Issue by beckerstef** [bassmaster187/TeslaLogger#857]
can anybody add Supercharger Hasselt to geofence ?

position can find here https://teslalogger.de/charging_time.php?id=178010

<img width="1676" alt="Supercharger Hasselt at Corda Campus" src="https://user-images.githubusercontent.com/37812574/185974009-901aa871-2add-4935-9bb5-080c678a2639.png">

**Comment by Arthur-Philip-Dent** [comment]
I can enter the Tesla charger and request a pull...
For the other charger locatio opposite, it would be nice to know at least the brand.

**Comment by beckerstef** [comment]
the dc chargers on the other side are under construction, I have not paid attention of the brand 🤷‍♂️

**Comment by Arthur-Philip-Dent** [comment]
Since there is no feedback on the provider for the "BE Corda Campus" until now, I'll request the entry with following address (and no general provider): 
BE Hasselt Corda Campus Kempische Steenweg 293,50.951484,5.353231,14

I adjusted the radius in coexistence with the opposite side Tesla SuC V3 not to overlap.
